version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  frontend:
    container_name: react-cloud
    tty: true
    build:
      context: ./cloud/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./cloud:/app
      - /app/node_modules
  
  backend:
    container_name: backend-express
    tty: true
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  my-db: