version: '3'

services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile.development
    ports:
      - "80:80"
    volumes:
      - ./proxy:/etc/nginx/conf.d
    networks:
      - noteapp-net
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'notes'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: '3307'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$$MYSQL_ROOT_PASSWORD","--protocol","tcp"]
    networks:
      - noteapp-net
  frontend:
    container_name: frontend
    tty: true
    build:
      context: ./frontend/
      dockerfile: Dockerfile.development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - noteapp-net
  backend:
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    tty: true
    build:
      context: ./backend/
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - noteapp-net
volumes:
  my-db:
networks:
  noteapp-net: